// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package audit

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseACTIONFromString Parse ACTION from string
func ParseACTIONFromString(str string) (ACTION, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := ACTION_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown ACTION: %s", str)
	}

	return ACTION(v), nil
}

// Equal type compare
func (t ACTION) Equal(target ACTION) bool {
	return t == target
}

// IsIn todo
func (t ACTION) IsIn(targets ...ACTION) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t ACTION) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *ACTION) UnmarshalJSON(b []byte) error {
	ins, err := ParseACTIONFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
