// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package cluster

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseKINDFromString Parse KIND from string
func ParseKINDFromString(str string) (KIND, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := KIND_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown KIND: %s", str)
	}

	return KIND(v), nil
}

// Equal type compare
func (t KIND) Equal(target KIND) bool {
	return t == target
}

// IsIn todo
func (t KIND) IsIn(targets ...KIND) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t KIND) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *KIND) UnmarshalJSON(b []byte) error {
	ins, err := ParseKINDFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}

// ParseINTERNAL_ACCESS_PROVIDERFromString Parse INTERNAL_ACCESS_PROVIDER from string
func ParseINTERNAL_ACCESS_PROVIDERFromString(str string) (INTERNAL_ACCESS_PROVIDER, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := INTERNAL_ACCESS_PROVIDER_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown INTERNAL_ACCESS_PROVIDER: %s", str)
	}

	return INTERNAL_ACCESS_PROVIDER(v), nil
}

// Equal type compare
func (t INTERNAL_ACCESS_PROVIDER) Equal(target INTERNAL_ACCESS_PROVIDER) bool {
	return t == target
}

// IsIn todo
func (t INTERNAL_ACCESS_PROVIDER) IsIn(targets ...INTERNAL_ACCESS_PROVIDER) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t INTERNAL_ACCESS_PROVIDER) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *INTERNAL_ACCESS_PROVIDER) UnmarshalJSON(b []byte) error {
	ins, err := ParseINTERNAL_ACCESS_PROVIDERFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}

// ParsePUBLIC_ACCESS_PROVIDERFromString Parse PUBLIC_ACCESS_PROVIDER from string
func ParsePUBLIC_ACCESS_PROVIDERFromString(str string) (PUBLIC_ACCESS_PROVIDER, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := PUBLIC_ACCESS_PROVIDER_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown PUBLIC_ACCESS_PROVIDER: %s", str)
	}

	return PUBLIC_ACCESS_PROVIDER(v), nil
}

// Equal type compare
func (t PUBLIC_ACCESS_PROVIDER) Equal(target PUBLIC_ACCESS_PROVIDER) bool {
	return t == target
}

// IsIn todo
func (t PUBLIC_ACCESS_PROVIDER) IsIn(targets ...PUBLIC_ACCESS_PROVIDER) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t PUBLIC_ACCESS_PROVIDER) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *PUBLIC_ACCESS_PROVIDER) UnmarshalJSON(b []byte) error {
	ins, err := ParsePUBLIC_ACCESS_PROVIDERFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
