// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package deploy

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseTRAFFIC_POLICYFromString Parse TRAFFIC_POLICY from string
func ParseTRAFFIC_POLICYFromString(str string) (TRAFFIC_POLICY, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := TRAFFIC_POLICY_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown TRAFFIC_POLICY: %s", str)
	}

	return TRAFFIC_POLICY(v), nil
}

// Equal type compare
func (t TRAFFIC_POLICY) Equal(target TRAFFIC_POLICY) bool {
	return t == target
}

// IsIn todo
func (t TRAFFIC_POLICY) IsIn(targets ...TRAFFIC_POLICY) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t TRAFFIC_POLICY) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *TRAFFIC_POLICY) UnmarshalJSON(b []byte) error {
	ins, err := ParseTRAFFIC_POLICYFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
