// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.0
// source: mpaas/apps/deploy/pb/rpc.proto

package deploy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPC_QueryDeployment_FullMethodName          = "/infraboard.mpaas.deploy.RPC/QueryDeployment"
	RPC_DescribeDeployment_FullMethodName       = "/infraboard.mpaas.deploy.RPC/DescribeDeployment"
	RPC_UpdateDeploymentStatus_FullMethodName   = "/infraboard.mpaas.deploy.RPC/UpdateDeploymentStatus"
	RPC_QueryDeploymentInjectEnv_FullMethodName = "/infraboard.mpaas.deploy.RPC/QueryDeploymentInjectEnv"
)

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RPC 应用部署配置
type RPCClient interface {
	// 查询部署列表
	QueryDeployment(ctx context.Context, in *QueryDeploymentRequest, opts ...grpc.CallOption) (*DeploymentSet, error)
	// 查询部署详情
	DescribeDeployment(ctx context.Context, in *DescribeDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	// 更新部署状态, moperator通过该rpc接口更新部署状态
	UpdateDeploymentStatus(ctx context.Context, in *UpdateDeploymentStatusRequest, opts ...grpc.CallOption) (*Deployment, error)
	// 查询部署是需要动态注入的环境变量, moperator 通过该接口拉取Env进行动态注入
	QueryDeploymentInjectEnv(ctx context.Context, in *QueryDeploymentInjectEnvRequest, opts ...grpc.CallOption) (*InjectionEnvGroupSet, error)
}

type rPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCClient(cc grpc.ClientConnInterface) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) QueryDeployment(ctx context.Context, in *QueryDeploymentRequest, opts ...grpc.CallOption) (*DeploymentSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentSet)
	err := c.cc.Invoke(ctx, RPC_QueryDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) DescribeDeployment(ctx context.Context, in *DescribeDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deployment)
	err := c.cc.Invoke(ctx, RPC_DescribeDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) UpdateDeploymentStatus(ctx context.Context, in *UpdateDeploymentStatusRequest, opts ...grpc.CallOption) (*Deployment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deployment)
	err := c.cc.Invoke(ctx, RPC_UpdateDeploymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) QueryDeploymentInjectEnv(ctx context.Context, in *QueryDeploymentInjectEnvRequest, opts ...grpc.CallOption) (*InjectionEnvGroupSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectionEnvGroupSet)
	err := c.cc.Invoke(ctx, RPC_QueryDeploymentInjectEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
// All implementations must embed UnimplementedRPCServer
// for forward compatibility.
//
// RPC 应用部署配置
type RPCServer interface {
	// 查询部署列表
	QueryDeployment(context.Context, *QueryDeploymentRequest) (*DeploymentSet, error)
	// 查询部署详情
	DescribeDeployment(context.Context, *DescribeDeploymentRequest) (*Deployment, error)
	// 更新部署状态, moperator通过该rpc接口更新部署状态
	UpdateDeploymentStatus(context.Context, *UpdateDeploymentStatusRequest) (*Deployment, error)
	// 查询部署是需要动态注入的环境变量, moperator 通过该接口拉取Env进行动态注入
	QueryDeploymentInjectEnv(context.Context, *QueryDeploymentInjectEnvRequest) (*InjectionEnvGroupSet, error)
	mustEmbedUnimplementedRPCServer()
}

// UnimplementedRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCServer struct{}

func (UnimplementedRPCServer) QueryDeployment(context.Context, *QueryDeploymentRequest) (*DeploymentSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDeployment not implemented")
}
func (UnimplementedRPCServer) DescribeDeployment(context.Context, *DescribeDeploymentRequest) (*Deployment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeDeployment not implemented")
}
func (UnimplementedRPCServer) UpdateDeploymentStatus(context.Context, *UpdateDeploymentStatusRequest) (*Deployment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeploymentStatus not implemented")
}
func (UnimplementedRPCServer) QueryDeploymentInjectEnv(context.Context, *QueryDeploymentInjectEnvRequest) (*InjectionEnvGroupSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDeploymentInjectEnv not implemented")
}
func (UnimplementedRPCServer) mustEmbedUnimplementedRPCServer() {}
func (UnimplementedRPCServer) testEmbeddedByValue()             {}

// UnsafeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServer will
// result in compilation errors.
type UnsafeRPCServer interface {
	mustEmbedUnimplementedRPCServer()
}

func RegisterRPCServer(s grpc.ServiceRegistrar, srv RPCServer) {
	// If the following call pancis, it indicates UnimplementedRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPC_ServiceDesc, srv)
}

func _RPC_QueryDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).QueryDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPC_QueryDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).QueryDeployment(ctx, req.(*QueryDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_DescribeDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).DescribeDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPC_DescribeDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).DescribeDeployment(ctx, req.(*DescribeDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_UpdateDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).UpdateDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPC_UpdateDeploymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).UpdateDeploymentStatus(ctx, req.(*UpdateDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_QueryDeploymentInjectEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeploymentInjectEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).QueryDeploymentInjectEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPC_QueryDeploymentInjectEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).QueryDeploymentInjectEnv(ctx, req.(*QueryDeploymentInjectEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPC_ServiceDesc is the grpc.ServiceDesc for RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infraboard.mpaas.deploy.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDeployment",
			Handler:    _RPC_QueryDeployment_Handler,
		},
		{
			MethodName: "DescribeDeployment",
			Handler:    _RPC_DescribeDeployment_Handler,
		},
		{
			MethodName: "UpdateDeploymentStatus",
			Handler:    _RPC_UpdateDeploymentStatus_Handler,
		},
		{
			MethodName: "QueryDeploymentInjectEnv",
			Handler:    _RPC_QueryDeploymentInjectEnv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpaas/apps/deploy/pb/rpc.proto",
}
