// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: apps/deploy/pb/rpc.proto

package deploy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCClient interface {
	UpdateDeployConfig(ctx context.Context, in *UpdateDeployConfigRequest, opts ...grpc.CallOption) (*DeployConfig, error)
	QueryDeployConfig(ctx context.Context, in *QueryDeployConfigRequest, opts ...grpc.CallOption) (*DeployConfigSet, error)
	DescribeDeployConfig(ctx context.Context, in *DescribeDeployConfigRequest, opts ...grpc.CallOption) (*DeployConfig, error)
	UpdateDeployConfigStatus(ctx context.Context, in *UpdateDeployConfigStatusRequest, opts ...grpc.CallOption) (*DeployConfig, error)
}

type rPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCClient(cc grpc.ClientConnInterface) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) UpdateDeployConfig(ctx context.Context, in *UpdateDeployConfigRequest, opts ...grpc.CallOption) (*DeployConfig, error) {
	out := new(DeployConfig)
	err := c.cc.Invoke(ctx, "/infraboard.mpaas.deploy.RPC/UpdateDeployConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) QueryDeployConfig(ctx context.Context, in *QueryDeployConfigRequest, opts ...grpc.CallOption) (*DeployConfigSet, error) {
	out := new(DeployConfigSet)
	err := c.cc.Invoke(ctx, "/infraboard.mpaas.deploy.RPC/QueryDeployConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) DescribeDeployConfig(ctx context.Context, in *DescribeDeployConfigRequest, opts ...grpc.CallOption) (*DeployConfig, error) {
	out := new(DeployConfig)
	err := c.cc.Invoke(ctx, "/infraboard.mpaas.deploy.RPC/DescribeDeployConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) UpdateDeployConfigStatus(ctx context.Context, in *UpdateDeployConfigStatusRequest, opts ...grpc.CallOption) (*DeployConfig, error) {
	out := new(DeployConfig)
	err := c.cc.Invoke(ctx, "/infraboard.mpaas.deploy.RPC/UpdateDeployConfigStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
// All implementations must embed UnimplementedRPCServer
// for forward compatibility
type RPCServer interface {
	UpdateDeployConfig(context.Context, *UpdateDeployConfigRequest) (*DeployConfig, error)
	QueryDeployConfig(context.Context, *QueryDeployConfigRequest) (*DeployConfigSet, error)
	DescribeDeployConfig(context.Context, *DescribeDeployConfigRequest) (*DeployConfig, error)
	UpdateDeployConfigStatus(context.Context, *UpdateDeployConfigStatusRequest) (*DeployConfig, error)
	mustEmbedUnimplementedRPCServer()
}

// UnimplementedRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (UnimplementedRPCServer) UpdateDeployConfig(context.Context, *UpdateDeployConfigRequest) (*DeployConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeployConfig not implemented")
}
func (UnimplementedRPCServer) QueryDeployConfig(context.Context, *QueryDeployConfigRequest) (*DeployConfigSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDeployConfig not implemented")
}
func (UnimplementedRPCServer) DescribeDeployConfig(context.Context, *DescribeDeployConfigRequest) (*DeployConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeDeployConfig not implemented")
}
func (UnimplementedRPCServer) UpdateDeployConfigStatus(context.Context, *UpdateDeployConfigStatusRequest) (*DeployConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeployConfigStatus not implemented")
}
func (UnimplementedRPCServer) mustEmbedUnimplementedRPCServer() {}

// UnsafeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServer will
// result in compilation errors.
type UnsafeRPCServer interface {
	mustEmbedUnimplementedRPCServer()
}

func RegisterRPCServer(s grpc.ServiceRegistrar, srv RPCServer) {
	s.RegisterService(&RPC_ServiceDesc, srv)
}

func _RPC_UpdateDeployConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeployConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).UpdateDeployConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.mpaas.deploy.RPC/UpdateDeployConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).UpdateDeployConfig(ctx, req.(*UpdateDeployConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_QueryDeployConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeployConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).QueryDeployConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.mpaas.deploy.RPC/QueryDeployConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).QueryDeployConfig(ctx, req.(*QueryDeployConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_DescribeDeployConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeDeployConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).DescribeDeployConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.mpaas.deploy.RPC/DescribeDeployConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).DescribeDeployConfig(ctx, req.(*DescribeDeployConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_UpdateDeployConfigStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeployConfigStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).UpdateDeployConfigStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.mpaas.deploy.RPC/UpdateDeployConfigStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).UpdateDeployConfigStatus(ctx, req.(*UpdateDeployConfigStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPC_ServiceDesc is the grpc.ServiceDesc for RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infraboard.mpaas.deploy.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDeployConfig",
			Handler:    _RPC_UpdateDeployConfig_Handler,
		},
		{
			MethodName: "QueryDeployConfig",
			Handler:    _RPC_QueryDeployConfig_Handler,
		},
		{
			MethodName: "DescribeDeployConfig",
			Handler:    _RPC_DescribeDeployConfig_Handler,
		},
		{
			MethodName: "UpdateDeployConfigStatus",
			Handler:    _RPC_UpdateDeployConfigStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/deploy/pb/rpc.proto",
}
