package trigger

const (
	// 事件提供商, 比如 GITLAB
	SYSTEM_VARIABLE_EVENT_PROVIDER = "EVENT_PROVIDER"
	// 事件类型, 平台统一定义, 比如 PUSH
	SYSTEM_VARIABLE_EVENT_TYPE = "EVENT_TYPE"
	// 事件描述, 比如 Push Hook
	SYSTEM_VARIABLE_EVENT_DESC = "EVENT_DESC"
	// 提供事件的实例 比如 "https://gitlab.com"
	SYSTEM_VARIABLE_EVENT_INSTANCE = "EVENT_INSTANCE"
	// 事件发生者UA 比如: "GitLab/15.5.0-pre"
	SYSTEM_VARIABLE_EVENT_USER_AGENT = "EVENT_USER_AGENT"
	// 事件Token, 这里固定为service id
	SYSTEM_VARIABLE_EVENT_TOKEN = "EVENT_TOKEN"
	// 事件的具体内容
	SYSTEM_VARIABLE_EVENT_CONTENT = "EVENT_CONTENT"

	// Git 项目相关变量
	// GitLab相关事件变量
	VARIABLE_GIT_PROJECT_NAME = "GIT_PROJECT_NAME"
	// Git 项目代码仓库SSH地址
	VARIABLE_GIT_SSH_URL = "GIT_SSH_URL"
	// Git 项目代码仓库HTTP地址
	VARIABLE_GIT_HTTP_URL = "GIT_HTTP_URL"
	// Git 项目分支
	VARIABLE_GIT_BRANCH = "GIT_BRANCH"
	// Git 项目Tag
	VARIABLE_GIT_TAG = "GIT_TAG"
	// Git 项目Commit号
	VARIABLE_GIT_COMMIT_ID = "GIT_COMMIT_ID"
)

const (
	GITLAB_HEADER_EVENT_NAME  = "X-Gitlab-Event"
	GITLAB_HEADER_EVENT_TOKEN = "X-Gitlab-Token"
	GITLAB_HEADER_INSTANCE    = "X-Gitlab-Instance"
	GITLAB_HEADER_EVENT_UUID  = "X-Gitlab-Event-UUID"
)
