// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package trigger

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseGITLAB_EVENT_TYPEFromString Parse GITLAB_EVENT_TYPE from string
func ParseGITLAB_EVENT_TYPEFromString(str string) (GITLAB_EVENT_TYPE, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := GITLAB_EVENT_TYPE_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown GITLAB_EVENT_TYPE: %s", str)
	}

	return GITLAB_EVENT_TYPE(v), nil
}

// Equal type compare
func (t GITLAB_EVENT_TYPE) Equal(target GITLAB_EVENT_TYPE) bool {
	return t == target
}

// IsIn todo
func (t GITLAB_EVENT_TYPE) IsIn(targets ...GITLAB_EVENT_TYPE) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t GITLAB_EVENT_TYPE) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *GITLAB_EVENT_TYPE) UnmarshalJSON(b []byte) error {
	ins, err := ParseGITLAB_EVENT_TYPEFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
