[app]
name = "mpaas"
key  = "this is your app key"

[http]
host = "127.0.0.1"
port = 8080

[grpc]
host = "127.0.0.1"
port = 18080

[mcenter]
address = "127.0.0.1:18010"
client_id = "zO21KkUrPxF2oPpF20qAmTjG"
client_secret = "9V1niHnU7XedTBYrCcxSI8LLDj5q5hFf"

[mongo]
endpoints = ["127.0.0.1:27017"]
database = "mpaas"

[log]
level = "debug"

[log.file]
enable = true

[trace]
enable = false
endpoint = "127.0.0.1:4318"