// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package task

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseDELETE_BYFromString Parse DELETE_BY from string
func ParseDELETE_BYFromString(str string) (DELETE_BY, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := DELETE_BY_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown DELETE_BY: %s", str)
	}

	return DELETE_BY(v), nil
}

// Equal type compare
func (t DELETE_BY) Equal(target DELETE_BY) bool {
	return t == target
}

// IsIn todo
func (t DELETE_BY) IsIn(targets ...DELETE_BY) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t DELETE_BY) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *DELETE_BY) UnmarshalJSON(b []byte) error {
	ins, err := ParseDELETE_BYFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
