// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: mpaas/apps/traffic/pb/rule.proto

package traffic

import (
	resource "github.com/infraboard/mcube/v2/pb/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对外访问的方式
type TARGET_TYPE int32

const (
	// 直接暴露部署的访问方式, 每个部署单独配置流量规则
	TARGET_TYPE_DEPLOY TARGET_TYPE = 0
	// 将多个部署做成一个负载均衡, 对外使用一个域名进行暴露, 一个集群配置一个流量规则
	TARGET_TYPE_CLUSTER TARGET_TYPE = 1
)

// Enum value maps for TARGET_TYPE.
var (
	TARGET_TYPE_name = map[int32]string{
		0: "DEPLOY",
		1: "CLUSTER",
	}
	TARGET_TYPE_value = map[string]int32{
		"DEPLOY":  0,
		"CLUSTER": 1,
	}
)

func (x TARGET_TYPE) Enum() *TARGET_TYPE {
	p := new(TARGET_TYPE)
	*p = x
	return p
}

func (x TARGET_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TARGET_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_mpaas_apps_traffic_pb_rule_proto_enumTypes[0].Descriptor()
}

func (TARGET_TYPE) Type() protoreflect.EnumType {
	return &file_mpaas_apps_traffic_pb_rule_proto_enumTypes[0]
}

func (x TARGET_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TARGET_TYPE.Descriptor instead.
func (TARGET_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_mpaas_apps_traffic_pb_rule_proto_rawDescGZIP(), []int{0}
}

type RuleSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 清单
	Items []*Rule `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RuleSet) Reset() {
	*x = RuleSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mpaas_apps_traffic_pb_rule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSet) ProtoMessage() {}

func (x *RuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_mpaas_apps_traffic_pb_rule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSet.ProtoReflect.Descriptor instead.
func (*RuleSet) Descriptor() ([]byte, []int) {
	return file_mpaas_apps_traffic_pb_rule_proto_rawDescGZIP(), []int{0}
}

func (x *RuleSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RuleSet) GetItems() []*Rule {
	if x != nil {
		return x.Items
	}
	return nil
}

// 部署集群
type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 元信息
	// @gotags: bson:",inline" json:"meta"
	Meta *resource.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta" bson:",inline"`
	// 创建信息
	// @gotags: bson:",inline" json:"spec"
	Spec *CreateRuleRequest `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec" bson:",inline"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mpaas_apps_traffic_pb_rule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_mpaas_apps_traffic_pb_rule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_mpaas_apps_traffic_pb_rule_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetMeta() *resource.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Rule) GetSpec() *CreateRuleRequest {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateRuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 被方法的目标类型, 比如部署/集群
	// @gotags: bson:"target_type" json:"target_type"
	TargetType TARGET_TYPE `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=infraboard.mpaas.traffic.TARGET_TYPE" json:"target_type" bson:"target_type"`
	// 目标的值, 具体的部署或者集群
	// @gotags: bson:"target_value" json:"target_value"
	TargetValue string `protobuf:"bytes,2,opt,name=target_value,json=targetValue,proto3" json:"target_value" bson:"target_value"`
	// 使用那个网关来暴露服务
	// @gotags: bson:"gateway_id" json:"gateway_id"
	GatewayId string `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id" bson:"gateway_id"`
	// 流量匹配规则
	// @gotags: bson:"rule" json:"rule"
	Rule string `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule" bson:"rule"`
	// 访问域名
	// @gotags: bson:"domain" json:"domain"
	Domain string `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain" bson:"domain"`
	// 权重
	// @gotags: bson:"deploy_weight" json:"deploy_weight"
	DeployWeight []*DeployWeight `protobuf:"bytes,6,rep,name=deploy_weight,json=deployWeight,proto3" json:"deploy_weight" bson:"deploy_weight"`
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mpaas_apps_traffic_pb_rule_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpaas_apps_traffic_pb_rule_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_mpaas_apps_traffic_pb_rule_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRuleRequest) GetTargetType() TARGET_TYPE {
	if x != nil {
		return x.TargetType
	}
	return TARGET_TYPE_DEPLOY
}

func (x *CreateRuleRequest) GetTargetValue() string {
	if x != nil {
		return x.TargetValue
	}
	return ""
}

func (x *CreateRuleRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *CreateRuleRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *CreateRuleRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateRuleRequest) GetDeployWeight() []*DeployWeight {
	if x != nil {
		return x.DeployWeight
	}
	return nil
}

type DeployWeight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 那个部署
	// @gotags: bson:"deploy" json:"deploy"
	Deploy string `protobuf:"bytes,1,opt,name=deploy,proto3" json:"deploy" bson:"deploy"`
	// 部署权重(0~100)
	// @gotags: bson:"weight" json:"weight"
	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight" bson:"weight"`
}

func (x *DeployWeight) Reset() {
	*x = DeployWeight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mpaas_apps_traffic_pb_rule_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWeight) ProtoMessage() {}

func (x *DeployWeight) ProtoReflect() protoreflect.Message {
	mi := &file_mpaas_apps_traffic_pb_rule_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWeight.ProtoReflect.Descriptor instead.
func (*DeployWeight) Descriptor() ([]byte, []int) {
	return file_mpaas_apps_traffic_pb_rule_proto_rawDescGZIP(), []int{3}
}

func (x *DeployWeight) GetDeploy() string {
	if x != nil {
		return x.Deploy
	}
	return ""
}

func (x *DeployWeight) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_mpaas_apps_traffic_pb_rule_proto protoreflect.FileDescriptor

var file_mpaas_apps_traffic_pb_rule_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x74, 0x72, 0x61,
	0x66, 0x66, 0x69, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x18, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d,
	0x70, 0x61, 0x61, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x1a, 0x1c, 0x6d, 0x63,
	0x75, 0x62, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x07, 0x52, 0x75,
	0x6c, 0x65, 0x53, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x34, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x74, 0x72,
	0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x7c, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x3f,
	0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e,
	0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x75,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22,
	0x96, 0x02, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x74, 0x72,
	0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x75, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x4b, 0x0a, 0x0d, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3e, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2a, 0x26, 0x0a, 0x0b, 0x54, 0x41, 0x52, 0x47,
	0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x50, 0x4c, 0x4f,
	0x59, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x10, 0x01,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2f,
	0x61, 0x70, 0x70, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mpaas_apps_traffic_pb_rule_proto_rawDescOnce sync.Once
	file_mpaas_apps_traffic_pb_rule_proto_rawDescData = file_mpaas_apps_traffic_pb_rule_proto_rawDesc
)

func file_mpaas_apps_traffic_pb_rule_proto_rawDescGZIP() []byte {
	file_mpaas_apps_traffic_pb_rule_proto_rawDescOnce.Do(func() {
		file_mpaas_apps_traffic_pb_rule_proto_rawDescData = protoimpl.X.CompressGZIP(file_mpaas_apps_traffic_pb_rule_proto_rawDescData)
	})
	return file_mpaas_apps_traffic_pb_rule_proto_rawDescData
}

var file_mpaas_apps_traffic_pb_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mpaas_apps_traffic_pb_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mpaas_apps_traffic_pb_rule_proto_goTypes = []interface{}{
	(TARGET_TYPE)(0),          // 0: infraboard.mpaas.traffic.TARGET_TYPE
	(*RuleSet)(nil),           // 1: infraboard.mpaas.traffic.RuleSet
	(*Rule)(nil),              // 2: infraboard.mpaas.traffic.Rule
	(*CreateRuleRequest)(nil), // 3: infraboard.mpaas.traffic.CreateRuleRequest
	(*DeployWeight)(nil),      // 4: infraboard.mpaas.traffic.DeployWeight
	(*resource.Meta)(nil),     // 5: infraboard.mcube.resource.Meta
}
var file_mpaas_apps_traffic_pb_rule_proto_depIdxs = []int32{
	2, // 0: infraboard.mpaas.traffic.RuleSet.items:type_name -> infraboard.mpaas.traffic.Rule
	5, // 1: infraboard.mpaas.traffic.Rule.meta:type_name -> infraboard.mcube.resource.Meta
	3, // 2: infraboard.mpaas.traffic.Rule.spec:type_name -> infraboard.mpaas.traffic.CreateRuleRequest
	0, // 3: infraboard.mpaas.traffic.CreateRuleRequest.target_type:type_name -> infraboard.mpaas.traffic.TARGET_TYPE
	4, // 4: infraboard.mpaas.traffic.CreateRuleRequest.deploy_weight:type_name -> infraboard.mpaas.traffic.DeployWeight
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mpaas_apps_traffic_pb_rule_proto_init() }
func file_mpaas_apps_traffic_pb_rule_proto_init() {
	if File_mpaas_apps_traffic_pb_rule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mpaas_apps_traffic_pb_rule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpaas_apps_traffic_pb_rule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpaas_apps_traffic_pb_rule_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mpaas_apps_traffic_pb_rule_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployWeight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mpaas_apps_traffic_pb_rule_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mpaas_apps_traffic_pb_rule_proto_goTypes,
		DependencyIndexes: file_mpaas_apps_traffic_pb_rule_proto_depIdxs,
		EnumInfos:         file_mpaas_apps_traffic_pb_rule_proto_enumTypes,
		MessageInfos:      file_mpaas_apps_traffic_pb_rule_proto_msgTypes,
	}.Build()
	File_mpaas_apps_traffic_pb_rule_proto = out.File
	file_mpaas_apps_traffic_pb_rule_proto_rawDesc = nil
	file_mpaas_apps_traffic_pb_rule_proto_goTypes = nil
	file_mpaas_apps_traffic_pb_rule_proto_depIdxs = nil
}
