// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: apps/approval/pb/deploy.proto

package approval

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STAGE int32

const (
	// 草稿
	STAGE_DRAFT STAGE = 0
	// 待审核
	STAGE_PENDDING STAGE = 1
	// 审核通过
	STAGE_PASSED STAGE = 2
	// 已过期
	STAGE_EXPIRED STAGE = 3
	// 审核拒绝
	STAGE_DENY STAGE = 4
	// 发布成功
	STAGE_SUCCEEDED STAGE = 11
	// 发布失败
	STAGE_FAILED STAGE = 12
	// 发布关闭, 发布成功后,验证没问题, 发布结束
	STAGE_CLOSED STAGE = 13
)

// Enum value maps for STAGE.
var (
	STAGE_name = map[int32]string{
		0:  "DRAFT",
		1:  "PENDDING",
		2:  "PASSED",
		3:  "EXPIRED",
		4:  "DENY",
		11: "SUCCEEDED",
		12: "FAILED",
		13: "CLOSED",
	}
	STAGE_value = map[string]int32{
		"DRAFT":     0,
		"PENDDING":  1,
		"PASSED":    2,
		"EXPIRED":   3,
		"DENY":      4,
		"SUCCEEDED": 11,
		"FAILED":    12,
		"CLOSED":    13,
	}
)

func (x STAGE) Enum() *STAGE {
	p := new(STAGE)
	*p = x
	return p
}

func (x STAGE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STAGE) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_approval_pb_deploy_proto_enumTypes[0].Descriptor()
}

func (STAGE) Type() protoreflect.EnumType {
	return &file_apps_approval_pb_deploy_proto_enumTypes[0]
}

func (x STAGE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STAGE.Descriptor instead.
func (STAGE) EnumDescriptor() ([]byte, []int) {
	return file_apps_approval_pb_deploy_proto_rawDescGZIP(), []int{0}
}

// 部署清单
type DeployList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 部署组数量
	// @gotags: bson:"total" json:"total"
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total" bson:"total"`
	// 部署组
	// @gotags: bson:"groups" json:"groups"
	Groups []*DeployGroup `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups" bson:"groups"`
}

func (x *DeployList) Reset() {
	*x = DeployList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_approval_pb_deploy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployList) ProtoMessage() {}

func (x *DeployList) ProtoReflect() protoreflect.Message {
	mi := &file_apps_approval_pb_deploy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployList.ProtoReflect.Descriptor instead.
func (*DeployList) Descriptor() ([]byte, []int) {
	return file_apps_approval_pb_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeployList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DeployList) GetGroups() []*DeployGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

// 部署组, 用来控制部署顺序, 组内的应用是并行部署的
type DeployGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 组名称
	// @gotags: bson:"name" json:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" bson:"name"`
	// 组描述
	// @gotags: bson:"describe" json:"describe"
	Describe string `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe" bson:"describe"`
	// 组编号, 排序使用
	// @gotags: bson:"index" json:"index"
	Index int64 `protobuf:"varint,3,opt,name=index,proto3" json:"index" bson:"index"`
	// 部署项数量
	// @gotags: bson:"total" json:"total"
	Total int64 `protobuf:"varint,4,opt,name=total,proto3" json:"total" bson:"total"`
	// 部署项
	// @gotags: bson:"items" json:"items"
	Items []*DeployItem `protobuf:"bytes,15,rep,name=items,proto3" json:"items" bson:"items"`
}

func (x *DeployGroup) Reset() {
	*x = DeployGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_approval_pb_deploy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployGroup) ProtoMessage() {}

func (x *DeployGroup) ProtoReflect() protoreflect.Message {
	mi := &file_apps_approval_pb_deploy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployGroup.ProtoReflect.Descriptor instead.
func (*DeployGroup) Descriptor() ([]byte, []int) {
	return file_apps_approval_pb_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *DeployGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployGroup) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *DeployGroup) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DeployGroup) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DeployGroup) GetItems() []*DeployItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 部署项
type DeployItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 部署设置
	// @gotags: bson:"spec,inline" json:"spec"
	Spec *RunDeployRequest `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec" bson:"spec,inline"`
	// 部署状态
	// @gotags: bson:"status" json:"status"
	Status *DeployStatus `protobuf:"bytes,15,opt,name=status,proto3" json:"status" bson:"status"`
}

func (x *DeployItem) Reset() {
	*x = DeployItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_approval_pb_deploy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployItem) ProtoMessage() {}

func (x *DeployItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_approval_pb_deploy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployItem.ProtoReflect.Descriptor instead.
func (*DeployItem) Descriptor() ([]byte, []int) {
	return file_apps_approval_pb_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *DeployItem) GetSpec() *RunDeployRequest {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DeployItem) GetStatus() *DeployStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type RunDeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 部署项Id,  组合格式: 发布单版本.组编号.部署编号, 用于状态更新定位
	// @gotags: bson:"_id" json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" bson:"_id"`
	// 部署项Id,  组合格式: 发布单版本.组编号.部署编号, 用于状态更新定位
	// @gotags: bson:"namespace" json:"namespace"
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace" bson:"namespace"`
	// 部署项Id,  组合格式: 发布单版本.组编号.部署编号, 用于状态更新定位
	// @gotags: bson:"domain" json:"domain"
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain" bson:"domain"`
	// 部署编号, 排序使用
	// @gotags: bson:"index" json:"index"
	Index int64 `protobuf:"varint,4,opt,name=index,proto3" json:"index" bson:"index"`
	// 部署配置Id
	// @gotags: bson:"deploy_config_id" json:"deploy_config_id"
	DeployConfigId string `protobuf:"bytes,5,opt,name=deploy_config_id,json=deployConfigId,proto3" json:"deploy_config_id" bson:"deploy_config_id"`
	// 部署的版本, 容器就填镜像版本, 包就填包的版本
	// @gotags: bson:"version" json:"version"
	Version string `protobuf:"bytes,6,opt,name=version,proto3" json:"version" bson:"version"`
	// 部署时注入的环境变量, 用于注入如发布单编号, 部署组 之类的信息
	// @gotags: bson:"deploy_env_vars" json:"deploy_env_vars"
	DeployEnvVars map[string]string `protobuf:"bytes,7,rep,name=deploy_env_vars,json=deployEnvVars,proto3" json:"deploy_env_vars" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"deploy_env_vars"`
}

func (x *RunDeployRequest) Reset() {
	*x = RunDeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_approval_pb_deploy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDeployRequest) ProtoMessage() {}

func (x *RunDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_approval_pb_deploy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDeployRequest.ProtoReflect.Descriptor instead.
func (*RunDeployRequest) Descriptor() ([]byte, []int) {
	return file_apps_approval_pb_deploy_proto_rawDescGZIP(), []int{3}
}

func (x *RunDeployRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RunDeployRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RunDeployRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RunDeployRequest) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RunDeployRequest) GetDeployConfigId() string {
	if x != nil {
		return x.DeployConfigId
	}
	return ""
}

func (x *RunDeployRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RunDeployRequest) GetDeployEnvVars() map[string]string {
	if x != nil {
		return x.DeployEnvVars
	}
	return nil
}

// 部署项状态
type DeployStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前状态
	// @gotags: bson:"stage" json:"stage"
	Stage STAGE `protobuf:"varint,1,opt,name=stage,proto3,enum=infraboard.mpaas.approval.STAGE" json:"stage" bson:"stage"`
	// 开始发布的时间
	// @gotags: bson:"start_at" json:"start_at"
	StartAt int64 `protobuf:"varint,2,opt,name=start_at,json=startAt,proto3" json:"start_at" bson:"start_at"`
	// 发布结束的时间
	// @gotags: bson:"end_at" json:"end_at"
	EndAt int64 `protobuf:"varint,3,opt,name=end_at,json=endAt,proto3" json:"end_at" bson:"end_at"`
	// 发布异常报错信息
	// @gotags: bson:"message" json:"message"
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message" bson:"message"`
	// 发布详细信息
	// @gotags: bson:"detail" json:"detail"
	Detail string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail" bson:"detail"`
}

func (x *DeployStatus) Reset() {
	*x = DeployStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_approval_pb_deploy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStatus) ProtoMessage() {}

func (x *DeployStatus) ProtoReflect() protoreflect.Message {
	mi := &file_apps_approval_pb_deploy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStatus.ProtoReflect.Descriptor instead.
func (*DeployStatus) Descriptor() ([]byte, []int) {
	return file_apps_approval_pb_deploy_proto_rawDescGZIP(), []int{4}
}

func (x *DeployStatus) GetStage() STAGE {
	if x != nil {
		return x.Stage
	}
	return STAGE_DRAFT
}

func (x *DeployStatus) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *DeployStatus) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *DeployStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_apps_approval_pb_deploy_proto protoreflect.FileDescriptor

var file_apps_approval_pb_deploy_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x2f,
	0x70, 0x62, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x19, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61,
	0x73, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x22, 0x62, 0x0a, 0x0a, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3e,
	0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61,
	0x73, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0xa6,
	0x01, 0x0a, 0x0b, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3b, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x61, 0x6c, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x3f, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c,
	0x2e, 0x52, 0x75, 0x6e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xdc, 0x02, 0x0a, 0x10, 0x52, 0x75, 0x6e,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x28, 0x0a, 0x10, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x66, 0x0a,
	0x0f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x65, 0x6e, 0x76, 0x5f, 0x76, 0x61, 0x72, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x61, 0x6c, 0x2e, 0x52, 0x75, 0x6e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x45, 0x6e, 0x76, 0x56, 0x61, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x45, 0x6e,
	0x76, 0x56, 0x61, 0x72, 0x73, 0x1a, 0x40, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x45,
	0x6e, 0x76, 0x56, 0x61, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xaa, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x2e, 0x53, 0x54, 0x41, 0x47, 0x45, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x64,
	0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x2a, 0x6a, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x47, 0x45, 0x12, 0x09, 0x0a,
	0x05, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x45, 0x4e, 0x44,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x41, 0x53, 0x53, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x0b, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x0c, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x0d,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2f,
	0x61, 0x70, 0x70, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_approval_pb_deploy_proto_rawDescOnce sync.Once
	file_apps_approval_pb_deploy_proto_rawDescData = file_apps_approval_pb_deploy_proto_rawDesc
)

func file_apps_approval_pb_deploy_proto_rawDescGZIP() []byte {
	file_apps_approval_pb_deploy_proto_rawDescOnce.Do(func() {
		file_apps_approval_pb_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_approval_pb_deploy_proto_rawDescData)
	})
	return file_apps_approval_pb_deploy_proto_rawDescData
}

var file_apps_approval_pb_deploy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_approval_pb_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apps_approval_pb_deploy_proto_goTypes = []interface{}{
	(STAGE)(0),               // 0: infraboard.mpaas.approval.STAGE
	(*DeployList)(nil),       // 1: infraboard.mpaas.approval.DeployList
	(*DeployGroup)(nil),      // 2: infraboard.mpaas.approval.DeployGroup
	(*DeployItem)(nil),       // 3: infraboard.mpaas.approval.DeployItem
	(*RunDeployRequest)(nil), // 4: infraboard.mpaas.approval.RunDeployRequest
	(*DeployStatus)(nil),     // 5: infraboard.mpaas.approval.DeployStatus
	nil,                      // 6: infraboard.mpaas.approval.RunDeployRequest.DeployEnvVarsEntry
}
var file_apps_approval_pb_deploy_proto_depIdxs = []int32{
	2, // 0: infraboard.mpaas.approval.DeployList.groups:type_name -> infraboard.mpaas.approval.DeployGroup
	3, // 1: infraboard.mpaas.approval.DeployGroup.items:type_name -> infraboard.mpaas.approval.DeployItem
	4, // 2: infraboard.mpaas.approval.DeployItem.spec:type_name -> infraboard.mpaas.approval.RunDeployRequest
	5, // 3: infraboard.mpaas.approval.DeployItem.status:type_name -> infraboard.mpaas.approval.DeployStatus
	6, // 4: infraboard.mpaas.approval.RunDeployRequest.deploy_env_vars:type_name -> infraboard.mpaas.approval.RunDeployRequest.DeployEnvVarsEntry
	0, // 5: infraboard.mpaas.approval.DeployStatus.stage:type_name -> infraboard.mpaas.approval.STAGE
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apps_approval_pb_deploy_proto_init() }
func file_apps_approval_pb_deploy_proto_init() {
	if File_apps_approval_pb_deploy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_approval_pb_deploy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_approval_pb_deploy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_approval_pb_deploy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_approval_pb_deploy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunDeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_approval_pb_deploy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_approval_pb_deploy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_approval_pb_deploy_proto_goTypes,
		DependencyIndexes: file_apps_approval_pb_deploy_proto_depIdxs,
		EnumInfos:         file_apps_approval_pb_deploy_proto_enumTypes,
		MessageInfos:      file_apps_approval_pb_deploy_proto_msgTypes,
	}.Build()
	File_apps_approval_pb_deploy_proto = out.File
	file_apps_approval_pb_deploy_proto_rawDesc = nil
	file_apps_approval_pb_deploy_proto_goTypes = nil
	file_apps_approval_pb_deploy_proto_depIdxs = nil
}
